<?php

/**
 * @file
 * Contains hbku.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hbku_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hbku module.
    case 'help.page.hbku':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hbku Custom Module') . '</p>';
      return $output;

    default:
  }
}
